### ISSUE TITLE
fast-crc32c fails to install on FreeBSD

### ISSUE THREAD

**Issue by citrin** [ashi009/node-fast-crc32c#11]
It is not possible to install fast-crc32c on FreeBSD because of fixed version for sse4_crc32 in package.json

Latest version of sse4_crc32 - 5.1.0 works on FreeBSD and older versions don't work.

Please update dependency version.

**Comment by ashi009** [comment]
Hi, Could you send me a one line PR for this?

**Comment by citrin** [comment]
sse4_crc32@5.1.1 is already installed by fast-crc32c@1.0.4. Error was with some old fast-crc32c version. Sorry to trouble you.

**Comment by ashi009** [comment]
no worries :)
