### ISSUE TITLE
Node 12 support - use N-API fork of `sse4_crc32`

### ISSUE THREAD

**Issue by grimen** [ashi009/node-fast-crc32c#14]
This library fails to install on **Node 12** because of dependency on non-maintained `sse4_crc32` library which is the cause of the incompatibility with Node 11+ - i.e. the classic `node-gyp` / NAN headache.

There is a Node.js **N-API** fork of `sse4_crc32` that works, and thus make `node-fast-crc32c` work with Node 12 as well - this is the fork:

https://github.com/ludios/sse4_crc32

...and PR:

https://github.com/anandsuresh/sse4_crc32/pull/71

It don't have big hopes it will be merged in a while because of the age of the issue thread, so if not this library can always use that as dependency instead?

There are `326` open-source projects depending on `node-fast-crc32c` in this very moment according to GitHub stats, so it is a bit of a pain right now - would be ideal to avoid more forks left and right.

**Comment by stephenplusplus** [comment]
sse4_crc32 updated with the fix, so now we just need this library to update to sse4_crc32@^6.0.0.

**Comment by ashi009** [comment]
Reopened due to #19.
