### ISSUE TITLE
Binary format

### ISSUE THREAD

**Issue by Ayms** [ashi009/node-fast-crc32c#2]
crc32c.calculate('Á').toString(16) gives 'b1cf5bcd' instead of '639bf696'

Suggested modification: ``buf= new Buffer(buf) --> buf = new Buffer(buf,'binary')``

See application in https://github.com/Ayms/bittorrent-nodeid

**Comment by ashi009** [comment]
[Buffer](https://nodejs.org/api/buffer.html#buffer_buffer)
> 'binary' - A way of encoding raw binary data into strings by using only the first 8 bits of each character. This encoding method is deprecated and should be avoided in favor of Buffer objects where possible. This encoding will be removed in future versions of Node.

`Á` (`0xC3` in extend-ASCII) as a non-ASCII character will be encoded in [UTF-8](http://en.wikipedia.org/wiki/UTF-8#Description) as `0xC381` (you found the character which happens to have the `0xC3` at first byte in ether UTF-8 encoding or extend-ASCII, but this is just a coincidence). 

As described above, binary mode will only keep `0xC3`, but it won't work for most other non-ASCII characters. (eg. `中文` (`0xE4B8AD` `0xE69687`) will become `0xE4 0xE6` `��`).

Thus, there is no bug need to be fixed.

**Comment by Ayms** [comment]
Yes, I know that binary is deprecated, the problem is that it is still widely used.

For example the project above must mimic what the boost c++ library is doing, which is processing crc32 byte by byte, so Á is 0xC1

I don't know what the rule should be for CRC32C, for you Á should be utf8 0xc381, is this specified somewhere?

Maybe you could add an option for binary use.

See https://github.com/Voxer/sse4_crc32/issues/26 too

**Comment by ashi009** [comment]
Pass a buffer directly to mitigate your problem:  
```js
crc32.calcuate(new Buffer([0xc1])).toString(16);
```
Note that any kind of CRC calculation is performed against bytes instead of characters.  If you feed boost implementation with `0xc381` you will get `0xb1cf5bcd`.  node.js (V8 to be precise) uses UTF-8 to encoding characters, whereas most C standard library uses [ASCII](http://en.wikipedia.org/wiki/C_string_handling) to encode string (char*) unless specify otherwise.

**Comment by Ayms** [comment]
>whereas most C standard library uses ASCII to encode string (char*) unless specify otherwise.

That's why you should consider an option, or document this behavior better, it's not trivial for people not used to CRC32C, that's not really a problem of mine, it's solved, I am more thinking to other people that might encounter it.
