### ISSUE TITLE
Wrong loading implementation on CPU without SSE 4.2. "Illegal instruction" occurs.

### ISSUE THREAD

**Issue by rkuzovlev** [ashi009/node-fast-crc32c#6]
I've tried to use "fast-crc32c" on CPU without sse42 supporting.
I had a error **Illegal instruction** on simple action ```node index.js```

My index.js
``` 
var rc32 = require('fast-crc32c');
```

Need to use ```sse4_crc32.isHardwareCrcSupported()``` function in ```loader.js``` to check sse42 supporting

**Comment by ashi009** [comment]
Could you paste the whole stack trace of the exception?

**Comment by rkuzovlev** [comment]
It's not JS error, i think it occurred into https://github.com/Voxer/sse4_crc32 c++ module.
```
user@host:/tmp/test$ node index.js
Illegal instruction
user@host:/tmp/test$
```

Your module using ```sse4_crc32.calculateOnHardware("The quick brown fox jumps over the lazy dog")``` directly without check by ```sse4_crc32.isHardwareCrcSupported()```.
But you can use ```sse4_crc32.calculate()``` without checking hardware support in both files ```sse4_crc32c_hw``` and ```sse4_crc32c_sw```

**Comment by ashi009** [comment]
Thanks. Apparently try-catch doesn't work with this level of exception, fixed.
